//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGE.Portal.HomePage {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class HomePage {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(HomePage target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::PGE.Portal.HomePage.HomePage @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <div id=\"slide\">\r\n\t\t<a href=\"#\" target=\"_blank\">\r\n\t\t\t<img src=\"/sites/pge" +
                        "portal/Style%20Library/images/slideshow/1.jpg\" alt=\"images1\" />\r\n\t\t</a>\r\n\t\t<a hr" +
                        "ef=\"#\" target=\"_blank\">\r\n\t\t\t<img src=\"/sites/pgeportal/Style%20Library/images/sl" +
                        "ideshow/2.jpg\" alt=\"images2\" />\r\n\t\t</a>\r\n\t\t<a href=\"#\" target=\"_blank\">\r\n\t\t\t<img" +
                        " src=\"/sites/pgeportal/Style%20Library/images/slideshow/3.jpg\" alt=\"images3\" />\r" +
                        "\n\t\t</a>\r\n\t\t<a href=\"#\" target=\"_blank\">\r\n\t\t\t<img src=\"/sites/pgeportal/Style%20L" +
                        "ibrary/images/slideshow/4.jpg\" alt=\"images4\" />\r\n\t\t</a>\r\n\t\t<a href=\"#\" target=\"_" +
                        "blank\">\r\n\t\t\t<img src=\"/sites/pgeportal/Style%20Library/images/slideshow/5.JPG\" a" +
                        "lt=\"images5\" />\r\n\t\t</a>\r\n\t\t<a href=\"#\" target=\"_blank\">\r\n\t\t\t<img src=\"/sites/pge" +
                        "portal/Style%20Library/images/slideshow/6.JPG\" alt=\"images6\" />\r\n\t\t</a>\r\n\r\n\t</di" +
                        "v>\r\n\r\n\t<script type=\"text/javascript\">\r\n\t\t$(\'#slide\').coinslider();\r\n\t</script>\r" +
                        "\n\t\t\t\t\t\t\r\n\t<div class=\"content\">\r\n\t\t<div class=\"content1\">\r\n\t\t\t<table id=\"tblMain" +
                        "Category\" class=\"table-content\"><tr>\r\n\t\t\t\t\t\t\t\r\n\t\t\t</tr></table>\r\n\t\t</div>\r\n\t\t\r\n\t" +
                        "\t\t\t\t\t\t\t\r\n\t\t<div class=\"gray-line\"></div>\r\n\t\t\t\t\t\t\t\r\n\t\t<div class=\"content1a\">\r\n\t\t" +
                        "\t<div class=\"title-content2\">Berita Terbaru</div>\r\n\t\t\t<div class=\"news-content2\"" +
                        ">\r\n\t\t\t\t<table class=\"small-table-content2\"><tr>\r\n\t\t\t\t\t<td><div class=\"date-conte" +
                        "nt2\">01 - Mei \r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r" +
                        "\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t- 2015</div></td>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<div class=\"small-title-" +
                        "content2\">\r\n\t\t\t\t\t\t\tPengumuman penerimaan karyawan \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n" +
                        "\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\tbaru 2015</div>\r\n" +
                        "\t\t\t\t\t\t<div class=\"small-news-content2\">\r\n\t\t\t\t\t\t\tHasil tes dan pengumuman \r\n\t\t\t\t\t" +
                        "\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t" +
                        "\t\t\t\t\t\tpenerimaan karyawan baru, untuk \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t" +
                        "\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\twilayah HuluBelu</div>\r\n\t\t\t\t\t" +
                        "</td>\r\n\t\t\t\t</tr><tr>\r\n\t\t\t\t\t<td><div class=\"date-content2\">01 - Mei \r\n\t\t\t\t\t\t\t\t\t\t\t" +
                        "\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t- 2015<" +
                        "/div></td>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<div class=\"small-title-content2\">\r\n\t\t\t\t\t\t\tPengumum" +
                        "an penerimaan karyawan \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r" +
                        "\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\tbaru 2015</div>\r\n\t\t\t\t\t\t<div class=\"small-new" +
                        "s-content2\">\r\n\t\t\t\t\t\t\tHasil tes dan pengumuman \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t" +
                        "\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\tpenerimaan karyawan b" +
                        "aru, untuk \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t" +
                        "\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\twilayah HuluBelu</div>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr></table>\r\n\t" +
                        "\t\t</div>\r\n\t\t</div>\r\n\t\t<div class=\"content2a\">\r\n\t\t\t<div class=\"title-content2\">Ac" +
                        "ara</div>\r\n\t\t\t<div class=\"news-content2\">\r\n\t\t\t\t<table class=\"small-table-content" +
                        "2\"><tr>\r\n\t\t\t\t\t<td><div class=\"date-content2\">01 - Mei \r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t" +
                        "\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t- 2015</div></td>\r\n\t" +
                        "\t\t\t\t<td>\r\n\t\t\t\t\t\t<div class=\"small-title-content2\">\r\n\t\t\t\t\t\t\tPengumuman penerimaan" +
                        " karyawan \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t" +
                        "\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\tbaru 2015</div>\r\n\t\t\t\t\t\t<div class=\"small-news-content2\">\r" +
                        "\n\t\t\t\t\t\t\tHasil tes dan pengumuman \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t" +
                        "\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\tpenerimaan karyawan baru, untuk \r\n" +
                        "\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t" +
                        "\t\t\r\n\t\t\t\t\t\t\twilayah HuluBelu</div>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr><tr>\r\n\t\t\t\t\t<td><div clas" +
                        "s=\"date-content2\">01 - Mei \r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r" +
                        "\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t- 2015</div></td>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<div class=" +
                        "\"small-title-content2\">\r\n\t\t\t\t\t\t\tPengumuman penerimaan karyawan \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t" +
                        "\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\tbaru" +
                        " 2015</div>\r\n\t\t\t\t\t\t<div class=\"small-news-content2\">\r\n\t\t\t\t\t\t\tHasil tes dan pengu" +
                        "muman \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t" +
                        "\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\tpenerimaan karyawan baru, untuk \r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r" +
                        "\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\twilayah HuluBelu" +
                        "</div>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr></table>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t<div clas" +
                        "s=\"gray-line\"></div>\r\n\t\t\t\t\t\t\t\r\n\t\t<div class=\"title-content3\">Area Kerja</div>\r\n\t" +
                        "\t<!-- #region Jssor Slider Begin -->\r\n\r\n\t\t<!-- Generated by Jssor Slider Maker O" +
                        "nline. -->\r\n\t\t<!-- This demo works without jquery library. -->\r\n\t\t\t\t\t\t\r\n\t\t<scrip" +
                        "t type=\"text/javascript\" src=\"/sites/PGEPortal/Style%20Library/jquery/jssor.slid" +
                        "er.min.js\"></script>\r\n\t\t<!-- use jssor.slider.debug.js instead for debug -->\r\n\t\t" +
                        "<script>\r\n\t\t\tjssor_1_slider_init = function () {\r\n\r\n\t\t\t\tvar jssor_1_options = {\r" +
                        "\n\t\t\t\t\t$AutoPlay: true,\r\n\t\t\t\t\t$AutoPlaySteps: 4,\r\n\t\t\t\t\t$SlideDuration: 160,\r\n\t\t\t\t" +
                        "\t$SlideWidth: 200,\r\n\t\t\t\t\t$SlideSpacing: 3,\r\n\t\t\t\t\t$Cols: 5,\r\n\t\t\t\t\t$ArrowNavigator" +
                        "Options: {\r\n\t\t\t\t\t\t$Class: $JssorArrowNavigator$,\r\n\t\t\t\t\t\t$Steps: 4\r\n\t\t\t\t\t},\r\n\t\t\t\t" +
                        "\t$BulletNavigatorOptions: {\r\n\t\t\t\t\t\t$Class: $JssorBulletNavigator$,\r\n\t\t\t\t\t\t$Spaci" +
                        "ngX: 1,\r\n\t\t\t\t\t\t$SpacingY: 1\r\n\t\t\t\t\t}\r\n\t\t\t\t};\r\n\r\n\t\t\t\tvar jssor_1_slider = new $Jss" +
                        "orSlider$(\"jssor_1\", jssor_1_options);\r\n\r\n\t\t\t\t//responsive code begin\r\n\t\t\t\t//you" +
                        " can remove responsive code if you don\'t want the slider scales while window res" +
                        "izes\r\n\t\t\t\tfunction ScaleSlider() {\r\n\t\t\t\t\tvar refSize = jssor_1_slider.$Elmt.pare" +
                        "ntNode.clientWidth;\r\n\t\t\t\t\tif (refSize) {\r\n\t\t\t\t\t\trefSize = Math.min(refSize, 809)" +
                        ";\r\n\t\t\t\t\t\tjssor_1_slider.$ScaleWidth(refSize);\r\n\t\t\t\t\t}\r\n\t\t\t\t\telse {\r\n\t\t\t\t\t\twindow" +
                        ".setTimeout(ScaleSlider, 30);\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t\tScaleSlider();\r\n\t\t\t\t$Jssor$.$A" +
                        "ddEvent(window, \"load\", ScaleSlider);\r\n\t\t\t\t$Jssor$.$AddEvent(window, \"resize\", $" +
                        "Jssor$.$WindowResizeFilter(window, ScaleSlider));\r\n\t\t\t\t$Jssor$.$AddEvent(window," +
                        " \"orientationchange\", ScaleSlider);\r\n\t\t\t\t//responsive code end\r\n\t\t\t};\r\n\t\t</scrip" +
                        "t>\r\n\t\t\t\t\t\t\t\r\n\t\t<div class=\"minislide\">\t\r\n\t\t\t<div class=\"minislidephoto\">\t\t\t\r\n\t\t\t" +
                        "\t<div id=\"jssor_1\" style=\"position: relative; margin: 0 auto; top: 0px; left: 0p" +
                        "x; width: 809px; height: 150px; visibility: hidden;\">\r\n\t\t\t\t\t<!-- Loading Screen " +
                        "-->\r\n\t\t\t\t\t<div data-u=\"loading\" style=\"position: absolute; top: 0px; left: 0px;\"" +
                        ">\r\n\t\t\t\t\t\t<div style=\"filter: alpha(opacity=70); opacity: 0.7; position: absolute" +
                        "; display: block; top: 0px; left: 0px; width: 100%; height: 100%;\"></div>\r\n\t\t\t\t\t" +
                        "\t<div style=\"position:absolute;display:block;background:url(\'/sites/PGEPortal/St" +
                        "yle%20Library/images/minislide/loading.gif\') no-repeat center center;top:0px;lef" +
                        "t:0px;width:100%;height:100%;\"></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div data-u=\"slides\" st" +
                        "yle=\"cursor: default; position: relative; top: 0px; left: 0px; width: 809px; hei" +
                        "ght: 150px; overflow: hidden;\">\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img" +
                        " data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images/minislide/005.jpg\" " +
                        "/>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\"" +
                        " src=\"/sites/pgeportal/Style%20Library/images/minislide/006.jpg\" />\r\n\t\t\t\t\t\t</div" +
                        ">\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pg" +
                        "eportal/Style%20Library/images/minislide/011.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div s" +
                        "tyle=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%2" +
                        "0Library/images/minislide/013.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: " +
                        "none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images" +
                        "/minislide/014.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t" +
                        "\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images/minislide/019." +
                        "jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"i" +
                        "mage\" src=\"/sites/pgeportal/Style%20Library/images/minislide/020.jpg\" />\r\n\t\t\t\t\t\t" +
                        "</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sit" +
                        "es/pgeportal/Style%20Library/images/minislide/021.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<" +
                        "div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/St" +
                        "yle%20Library/images/minislide/022.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"disp" +
                        "lay: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/i" +
                        "mages/minislide/024.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t" +
                        "\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images/minislide" +
                        "/025.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data" +
                        "-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images/minislide/027.jpg\" />\r\n\t" +
                        "\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=" +
                        "\"/sites/pgeportal/Style%20Library/images/minislide/029.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t" +
                        "\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeport" +
                        "al/Style%20Library/images/minislide/030.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=" +
                        "\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%20Libr" +
                        "ary/images/minislide/031.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;" +
                        "\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images/mini" +
                        "slide/030.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img" +
                        " data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images/minislide/034.jpg\" " +
                        "/>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\"" +
                        " src=\"/sites/pgeportal/Style%20Library/images/minislide/038.jpg\" />\r\n\t\t\t\t\t\t</div" +
                        ">\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pg" +
                        "eportal/Style%20Library/images/minislide/039.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div s" +
                        "tyle=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%2" +
                        "0Library/images/minislide/043.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: " +
                        "none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images" +
                        "/minislide/044.jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t" +
                        "\t<img data-u=\"image\" src=\"/sites/pgeportal/Style%20Library/images/minislide/047." +
                        "jpg\" />\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style=\"display: none;\">\r\n\t\t\t\t\t\t\t<img data-u=\"i" +
                        "mage\" src=\"/sites/pgeportal/Style%20Library/images/minislide/050.jpg\" />\r\n\t\t\t\t\t\t" +
                        "</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t\t<!-- Bullet Navigator -->\r\n\t\t\t\t<div data-u=" +
                        "\"navigator\" class=\"jssorb03\" style=\"bottom:10px;right:10px;\">\r\n\t\t\t\t\t<!-- bullet " +
                        "navigator item prototype -->\r\n\t\t\t\t\t<div data-u=\"prototype\" style=\"width:21px;hei" +
                        "ght:21px;\">\r\n\t\t\t\t\t\t<div data-u=\"numbertemplate\"></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r" +
                        "\n\t\t\t</div>\r\n\t\t\t\t\t\t    \t\r\n\t\t\t<!-- Arrow Navigator -->\r\n\t\t\t<span data-u=\"arrowleft" +
                        "\" class=\"jssora03l\" data-autocenter=\"2\"></span>\r\n\t\t\t<span data-u=\"arrowright\" cl" +
                        "ass=\"jssora03r\" data-autocenter=\"2\"></span>\r\n\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t<script>\r\n\t\t\tj" +
                        "ssor_1_slider_init();\r\n\t\t</script>\r\n\t\t\t\t\t\t\r\n\t\t<!-- #endregion Jssor Slider End -" +
                        "->\r\n\t</div>\r\n\r\n\r\n<script src=\"../_layouts/15/PGE.Portal/js/HomePage.js\"></script" +
                        ">\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
